### ISSUE TITLE
Uprava katalogu

### ISSUE THREAD

**Issue by bordac6** [TIS2017/SpektroskopickeData#12]
Treba upravit katalog poziadaviek na zaklade pripomienok.

- Tento dokument popisuje požiadavky projektu...

=> požiadavky zadávateľa na softvér vyvíjaný v projekte...

chýba tam: pre koho je dokument určený?

- skratka pre dynamicky spojenú knižnicu

=> takyto preklad DLL-ka som este nepocul

- nadstavba c++

=> nene, labview nie je nadstavba c++, je to samostatne vyvojove

prostredie s vlastnym jazykom

- k 3. kapitole:

=> napriek tomu, ze vas softver bude robit vedecko-technicky

vypocet, aj tak treba poziadavky zapisat v style katalogu poziadaviek.

Vo vasom pripade to znamena, ze definujete spravanie vasho komponentu

a stale plati, ze kazda jedna atomicka poziadavka by mala byt oznacena

cislom.

t.j. nieco v takomto style:

3.1. DLL bude obsahovat tri funkcie f1, f2, f3.

3.2. Funkcia f1 pocita janko-hraskov algoritmus derivacie podla odkazu

[3] uvedeneho v stati 1.4

3.3. Vstupom funkcie f1 su tri argumenty: a : int, b : double, c : string

3.4 Argument a funkcie f1 moze byt kladny, ak svieti slnko, inak je zaporny.

3.5. Argument c funkcie f1 musi obsahovat frazu "formula 1"

3.6. Vystupom funkcie f1 je boolean

3.7. atd. atd....

**Comment by pavelpetrovic** [comment]
nahrávam súbor s mojimi komentármi.
[KatalogPoziadaviek_2017_Frantisek_s_pripomienkami.docx](https://github.com/TIS2017/SpektroskopickeData/files/1446516/KatalogPoziadaviek_2017_Frantisek_s_pripomienkami.docx)

 -

**Comment by bordac6** [comment]
Nahrávam súbor s otázkami na zadávateľa a poznámkami, ako plánujem upraviť dokument.
[KatalogPoziadaviek_2017_Frantisek_s_otazkami.docx](https://github.com/TIS2017/SpektroskopickeData/files/1450086/KatalogPoziadaviek_2017_Frantisek_s_otazkami.docx)
