### ISSUE TITLE
je tu málo issues

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2017/SpektroskopickeData#7]
to sa okrem katalógu požiadaviek na ničom inom nerobí?

VŠETKO, na čom na projekte robíte, MUSÍ mať vytvorený issue.
Komunikácia o tom, čo sa robí, prebieha tu.
Napravte to a potom tento issue zatvorte.

**Comment by bordac6** [comment]
VSETKO na com sme pracovali a na com pracujeme uz ma issue.
